apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: cinder
    meta.helm.sh/release-namespace: openstack
  creationTimestamp: "2025-07-06T07:35:03Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: cinder
  namespace: openstack
  resourceVersion: "1912938"
  uid: 5713c5b2-7c18-4994-b164-4807d891e5e4
spec:
  clusterIP: 10.96.168.10
  clusterIPs:
  - 10.96.168.10
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: ingress-api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
