apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: neutron
    meta.helm.sh/release-namespace: openstack
  creationTimestamp: "2025-07-06T08:18:26Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: neutron
  namespace: openstack
  resourceVersion: "1921696"
  uid: a261d760-afa3-4497-83f5-438eda08b27b
spec:
  clusterIP: 10.96.36.212
  clusterIPs:
  - 10.96.36.212
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: ingress-api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
