version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    container_name: minicloud-backend-dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./backend/src:/app/src
    networks:
      - minicloud-network

  frontend:
    image: node:18-alpine
    container_name: minicloud-frontend-dev
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    networks:
      - minicloud-network

networks:
  minicloud-network:
    driver: bridge
