apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glance-images
  namespace: openstack
  labels:
    application: glance
    component: api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: general
