# 개발환경 전용 설정
logging:
  level:
    root: INFO
    com.minicloud: DEBUG
    org.springframework.web.reactive.function.client: DEBUG

# OpenStack 개발환경 (keystone 서비스를 통한 접근)
openstack:
  auth:
    url: "http://keystone.openstack.svc.cluster.local/v3"
  services:
    nova: "http://nova.openstack.svc.cluster.local/v2.1"
    neutron: "http://neutron.openstack.svc.cluster.local/v2.0"
    cinder: "http://cinder.openstack.svc.cluster.local/v3"
    glance: "http://glance.openstack.svc.cluster.local/v2"
