# 개발환경 전용 설정
logging:
  level:
    root: INFO
    com.minicloud: DEBUG
    org.springframework.web.reactive.function.client: DEBUG

# OpenStack 개발환경 (로컬에서 테스트할 때)
openstack:
  auth:
    url: "http://172.24.128.100/v3"
  services:
    nova: "http://172.24.128.100/v2.1"
    neutron: "http://172.24.128.100/v2.0"
    cinder: "http://172.24.128.100/v3"
    glance: "http://172.24.128.100/v2"
