server:
  port: 8080
  address: 0.0.0.0  # 모든 인터페이스에서 접근 허용
  servlet:
    context-path: /
    session:
      timeout: 30m

spring:
  application:
    name: mini-cloud-backend
  
  # 세션 설정
  session:
    store-type: none  # 메모리 세션 (개발용)
    timeout: 1800s    # 30분
  
  # 보안 설정
  security:
    user:
      name: admin
      password: admin

# OpenStack 설정
openstack:
  auth:
    url: "http://keystone.openstack.svc.cluster.local/v3"
    username: "admin"
    password: "password"
    project: "admin"
    domain: "default"
  services:
    nova: "http://nova.openstack.svc.cluster.local"
    neutron: "http://neutron.openstack.svc.cluster.local"
    cinder: "http://cinder.openstack.svc.cluster.local"
    glance: "http://glance.openstack.svc.cluster.local"

# API 문서화
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

# 로깅
logging:
  level:
    com.minicloud: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

# CORS 설정
cors:
  allowed-origins: 
    - "http://localhost:3000"
    - "http://localhost:5173"
    - "http://192.168.219.113:3000"
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: true
