#################################################################################################################
# Ceph 블록 스토리지 풀 정의 파일 (namespace: ceph)
# 
# 이 파일은 RBD (RADOS Block Device) 스토리지 풀을 정의합니다.
# OpenStack의 Cinder 볼륨 스토리지와 Kubernetes PV에서 사용됩니다.
#
# 3노드 mini-cloud 환경 최적화:
# - master, worker1, worker2 노드에 분산 저장
# - 복제본 3개로 고가용성 보장
#################################################################################################################

apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: ceph # ceph namespace 사용
  labels:
    # 블록 풀 식별 레이블
    pool-type: "block"
    storage-class: "replicated"
    # OpenStack 연동 레이블
    openstack-compatible: "true"
spec:
  # ============================================================================
  # 복제 설정 - 데이터 안정성과 가용성
  # ============================================================================
  
  replicated:
    # 복제본 개수 (3노드 환경에서 권장: 3개)
    # size: 1 - 복제본 없음 (테스트 전용, 데이터 손실 위험)
    # size: 2 - 최소 복제본 (노드 1개 장애 허용)
    # size: 3 - 권장 복제본 (노드 2개 장애 허용, 프로덕션 권장)
    size: 3
    
    # 최소 복제본 개수 (쓰기 작업을 위한 최소 가용 복제본)
    # 일반적으로 (size + 1) / 2로 설정
    # size 3인 경우 minSize 2가 권장됨
    requireSafeReplicaSize: true
    
    # 하위 장애 도메인 설정 (선택사항)
    # subFailureDomain: "rack"
    
    # 복제본 분산을 위한 추가 설정
    # replicasPerFailureDomain: 1

  # ============================================================================
  # 장애 도메인 설정 - 데이터 분산 전략
  # ============================================================================
  
  # 장애 도메인 레벨 정의
  # - osd: OSD 레벨 분산 (동일 노드 내 다른 OSD)
  # - host: 호스트 레벨 분산 (다른 노드에 분산) ← 3노드 환경에서 권장
  # - rack: 랙 레벨 분산 (데이터센터 환경)
  # - zone: 존 레벨 분산 (멀티 존 환경)
  failureDomain: host

  # ============================================================================
  # 압축 설정 - 스토리지 효율성 (선택사항)
  # ============================================================================
  
  # 데이터 압축 활성화 (스토리지 공간 절약)
  # compression:
  #   # 압축 알고리즘: none, snappy, zlib, zstd, lz4
  #   algorithm: lz4
  #   # 압축 모드: none, passive, aggressive, force
  #   mode: passive
  #   # 압축 최소 크기 (바이트)
  #   minBlobSize: 65536
  #   # 압축 최대 크기 (바이트)  
  #   maxBlobSize: 1048576

  # ============================================================================
  # 배치 그룹 설정 - 성능 최적화 (선택사항)
  # ============================================================================
  
  # Placement Group (PG) 개수 설정
  # 자동 계산을 위해 주석 처리 (Ceph가 자동으로 최적값 계산)
  # parameters:
  #   # PG 개수 (일반적으로 OSD 수 * 100 / 복제본 수)
  #   # 3노드 환경에서 각 노드에 1개 OSD가 있다면: 3 * 100 / 3 = 100
  #   # 2의 거듭제곱에 가까운 값으로 설정: 128
  #   pg_num: "128"
  #   pgp_num: "128"
  #   
  #   # PG 자동 스케일링 모드
  #   pg_autoscale_mode: "on"
  #   
  #   # 대상 크기 비율 (전체 클러스터 대비 이 풀이 사용할 비율)
  #   target_size_ratio: "0.5"

  # ============================================================================
  # 미러링 설정 - 다중 클러스터 복제 (고급 기능, 선택사항)
  # ============================================================================
  
  # RBD 미러링 활성화 (재해 복구용)
  # mirroring:
  #   enabled: false
  #   # 미러링 모드: pool (풀 전체) 또는 image (이미지별)
  #   mode: pool
  #   # 스냅샷 기반 미러링
  #   snapshotSchedules:
  #     - interval: "24h"
  #       startTime: "14:00:00-05:00"
  #   # 피어 클러스터 정보
  #   peers:
  #     secretNames:
  #       - pool-peer1

  # ============================================================================
  # 쿼터 설정 - 리소스 제한 (선택사항)
  # ============================================================================
  
  # 풀별 쿼터 설정
  # quotas:
  #   # 최대 오브젝트 개수
  #   maxObjects: 1000000
  #   # 최대 바이트 크기 (예: 1TB)
  #   maxSize: "1Ti"

  # ============================================================================
  # 성능 최적화 설정 (고급 옵션)
  # ============================================================================
  
  # 풀별 애플리케이션 태그 (RBD 전용)
  # 이 설정은 Ceph가 풀 용도를 이해하고 최적화하는 데 도움
  # application: rbd

---
#################################################################################################################
# 추가 블록 풀 정의 예시 (필요시 사용)
#
# OpenStack 환경에서는 용도별로 여러 풀을 생성할 수 있습니다:
# - volumes: 일반 볼륨용
# - images: Glance 이미지용  
# - vms: 인스턴스 디스크용
# - backups: 백업용
#################################################################################################################

# OpenStack Glance 이미지용 별도 풀 (필요시 주석 해제)
# ---
# apiVersion: ceph.rook.io/v1
# kind: CephBlockPool
# metadata:
#   name: images
#   namespace: ceph
#   labels:
#     pool-type: "block"
#     openstack-service: "glance"
# spec:
#   replicated:
#     size: 3
#     requireSafeReplicaSize: true
#   failureDomain: host
#   # 이미지는 읽기 위주이므로 압축 활성화 고려
#   compression:
#     algorithm: lz4
#     mode: passive

# OpenStack 백업용 별도 풀 (필요시 주석 해제)
# ---
# apiVersion: ceph.rook.io/v1  
# kind: CephBlockPool
# metadata:
#   name: backups
#   namespace: ceph
#   labels:
#     pool-type: "block"
#     openstack-service: "cinder-backup"
# spec:
#   replicated:
#     size: 2  # 백업용이므로 복제본 수 줄여서 공간 절약
#     requireSafeReplicaSize: true
#   failureDomain: host
#   compression:
#     algorithm: zstd  # 백업은 압축률 우선
#     mode: aggressive